Implementation of the various scan() functions
kjobanputra/terrier pull request #3
Opened 2020-02-24 21:04 UTC by CalLavicka

Implementation of ScanKey(), ScanAscending(), ScanDescending(), and ScanLimitDescending(). 

Can't test until insert() is done, but we should probably merge this in fairly soon because there are some important things which you guys will need, like the key comparison functions, a constructor (to be filled in), and some friend classing.

2020-02-25 03:02 UTC, alex-stanescu requested changes

2020-02-25 03:24 UTC, alex-stanescu requested changes
Smol

2020-02-25 03:30 UTC, alex-stanescu approved these changes

2020-02-26 00:09 UTC, kjobanputra approved these changes

2020-02-26 00:20 UTC, merged